version: '3.8'

services:
  # server:
  #   build: ./server
  #   volumes:
  #     - ./server:/usr/src/app/server
  #     - /usr/src/app/server/node_modules
  #   ports:
  #     - 5000:5000
  #   environment:
  #     - JWT_SECRET=forbiddenfruit
  #     - EMAIL_PASSWORD=Y5$$6RPCs3jOW
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_DB=siab
  #     - POSTGRES_PASS=admin123hehehe
  #     - POSTGRES_HOST=siab-db-v0.cvknyozdfapx.us-east-2.rds.amazonaws.com
  #     - POSTGRES_PORT=5432

  client:
    build:
      context: ./client
      args:
        - REACT_APP_BASE_URL=http://api.siagaairbersih.com
        - REACT_APP_MAP_API=AIzaSyDw6-MBsHBhZqS4DSDBlXGr1fO_21Y6PQI
        - REACT_APP_JWT_SECRET=forbiddenfruit
    volumes:
      - /etc/letsencrypt/live/akun.siagaairbersih.com:/etc/nginx/certs
      - ./client:/usr/src/app/client
      - /usr/src/app/client/node_modules
    ports:
      - 80:80

  # postgresdb:
  #   image: 'postgres:12.4-alpine'
  #   ports:
  #     - 5432:5432
  #   volumes:
  #     - ./pgdata:/var/lib/postgresql/data
  #   environment:
  #     POSTGRES_PASSWORD: admin
